# Generated by Django 5.1 on 2024-09-14 06:33

import accounts.services
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='Телефон')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='имя')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='фамилия')),
                ('age', models.SmallIntegerField(blank=True, default=18, verbose_name='возраст')),
                ('avatar', models.ImageField(default='profiles/avatar.png', upload_to=accounts.services.get_path_avatar_for_user, verbose_name='Аватар')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Подтвержден')),
                ('club_member', models.BooleanField(default=False, verbose_name='Член клуба')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='registered')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expiration', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification_tokens', to='accounts.user')),
            ],
            options={
                'verbose_name': 'Верификация почты',
                'verbose_name_plural': 'Верификация почты',
            },
        ),
    ]
